package com.example.trackhealth;

import android.os.Bundle;

import androidx.appcompat.widget.SearchView;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;


public class Knowledge_medicine_fragment extends Fragment {

 RecyclerView firsrecyv, secondrecycleview, thirdrecycleview, fourrecycleview;
 SearchView searchView;

 List<List> simpleone = new ArrayList<>();
 List<String> arr = new ArrayList<>();
 MedicineExtraAdapter2 bestSellerAdapter;
 MedicineExtraAdapter2 bestSeller;
 MedicineExtraAdapter1 newAdapter1;
 MedicineExtraAdapter1 newAdapter2;


 @Override
 public View onCreateView(LayoutInflater inflater, ViewGroup container,
                          Bundle savedInstanceState) {

  View view = inflater.inflate(R.layout.fragment_knowledge_medicine_fragment, container, false);

  searchView = view.findViewById(R.id.searchview);
  searchView.setBackgroundColor(getResources().getColor(R.color.white));
  int textColor = getResources().getColor(R.color.black);
  EditText editText = searchView.findViewById(androidx.appcompat.R.id.search_src_text);
  editText.setTextColor(textColor);
  editText.setHintTextColor(textColor);
  ImageView closeButton = searchView.findViewById(androidx.appcompat.R.id.search_close_btn);
  closeButton.setColorFilter(textColor);
  ImageView searchIcon = searchView.findViewById(androidx.appcompat.R.id.search_button);
  searchIcon.setColorFilter(textColor);


  // first reycleview
  firsrecyv = view.findViewById(R.id.First_recycleview);
  firsrecyv.setHasFixedSize(true);
  firsrecyv.setLayoutManager(new LinearLayoutManager(getContext(), LinearLayoutManager.HORIZONTAL, false));
  simpleone.add(new ArrayList<>(Arrays.asList("Amoxicillin", "Amoxicillin is a penicillin antibiotic that fights bacteria. Amoxicillin is used to treat many different types of infection caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ciprofloxacin", "Ciprofloxacin is a fluoroquinolone antibiotic that fights bacteria in the body. It is used to treat different types of bacterial infections, including urinary tract infections, respiratory infections, skin infections, joint and bone infections, and certain types of infectious diarrhea.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Sodium Nitroprusside", "Sodium nitroprusside is a vasodilator medication that improves blood flow by relaxing blood vessels. It is used to treat high blood pressure and heart failure.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Hydrochlorothiazide", "Hydrochlorothiazide is a thiazide diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure and edema (fluid retention)", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Doxycycline", "Doxycycline is a tetracycline antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including acne, urinary tract infections, intestinal infections, eye infections, gonorrhea, chlamydia, periodontitis (gum disease), and others.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Metronidazole", "Metronidazole is an antibiotic that fights bacteria and parasites in the body. It is used to treat bacterial infections of the vagina, stomach, skin, joints, and respiratory tract. It is also used to treat certain sexually transmitted infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Azithromycin", "Azithromycin is a macrolide antibiotic that fights bacteria. It is used to treat many different types of infections caused by bacteria, including respiratory infections, skin infections, ear infections, and sexually transmitted diseases.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clarithromycin", "Clarithromycin is a macrolide antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections affecting the skin and respiratory system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clindamycin", "Clindamycin is a lincosamide antibiotic that fights bacteria in the body. It is used to treat serious infections caused by bacteria, including skin infections, respiratory infections, pelvic infections, and other infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Erythromycin", "Erythromycin is a macrolide antibiotic that fights bacteria. It is used to treat or prevent many different types of infections caused by bacteria, such as respiratory tract infections, skin infections, ear infections, and sexually transmitted diseases.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Gentamicin", "Gentamicin is an aminoglycoside antibiotic that fights bacteria. It is used to treat severe or serious bacterial infections, including respiratory tract infections, urinary tract infections, blood infections, and skin infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Levofloxacin", "Levofloxacin is a fluoroquinolone antibiotic that fights bacteria in the body. It is used to treat different types of bacterial infections, including sinus infections, skin infections, urinary tract infections, prostate infections, and pneumonia.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Nitrofurantoin", "Nitrofurantoin is an antibiotic that fights bacteria in the body. It is used to treat urinary tract infections caused by certain types of bacteria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Trimethoprim-Sulfamethoxazole", "Trimethoprim-sulfamethoxazole is a combination antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including urinary tract infections, respiratory infections, intestinal infections, and ear infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Vancomycin", "Vancomycin is a glycopeptide antibiotic that fights bacteria in the body. It is used to treat severe bacterial infections, including bloodstream infections, bone infections, joint infections, skin infections, and lower respiratory tract infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Amikacin", "Amikacin is an aminoglycoside antibiotic that fights bacteria. It is used to treat serious or severe bacterial infections, including bloodstream infections, bone infections, joint infections, abdominal infections, and skin infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ceftriaxone", "Ceftriaxone is a cephalosporin antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including respiratory tract infections, skin infections, urinary tract infections, and bone infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Cefotaxime", "Cefotaxime is a cephalosporin antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including respiratory tract infections, skin infections, urinary tract infections, and abdominal infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ceftazidime", "Ceftazidime is a cephalosporin antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including respiratory tract infections, skin infections, urinary tract infections, and abdominal infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Cefepime", "Cefepime is a cephalosporin antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including respiratory tract infections, skin infections, urinary tract infections, and abdominal infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Meropenem", "Meropenem is a carbapenem antibiotic that fights bacteria in the body. It is used to treat severe or serious bacterial infections, including bloodstream infections, abdominal infections, skin infections, and pneumonia.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Imipenem-Cilastatin", "Imipenem-cilastatin is a carbapenem antibiotic that fights bacteria in the body. It is used to treat severe or serious bacterial infections, including abdominal infections, skin infections, urinary tract infections, and pneumonia.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Aztreonam", "Aztreonam is a monobactam antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including respiratory tract infections, skin infections, urinary tract infections, and abdominal infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Linezolid", "Linezolid is an oxazolidinone antibiotic that fights bacteria in the body. It is used to treat severe or serious bacterial infections, including bloodstream infections, skin infections, and pneumonia.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Daptomycin", "Daptomycin is a cyclic lipopeptide antibiotic that fights bacteria in the body. It is used to treat severe or serious bacterial infections, including bloodstream infections, skin infections, and pneumonia.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Tigecycline", "Tigecycline is a glycylcycline antibiotic that fights bacteria in the body. It is used to treat complicated skin and skin structure infections, complicated intra-abdominal infections, and community-acquired bacterial pneumonia.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Colistin", "Colistin is a polymyxin antibiotic that fights bacteria in the body. It is used to treat serious or severe bacterial infections, including bloodstream infections, lung infections, and urinary tract infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Polymyxin B", "Polymyxin B is a polymyxin antibiotic that fights bacteria in the body. It is used to treat serious or severe bacterial infections, including bloodstream infections, lung infections, and urinary tract infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Rifampin", "Rifampin is a rifamycin antibiotic that fights bacteria in the body. It is used to treat many different types of bacterial infections, including tuberculosis, meningitis, and leprosy.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Isoniazid", "Isoniazid is an antibiotic that fights bacteria in the body. It is used to treat tuberculosis and prevent tuberculosis in people who have been exposed to the disease.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Pyrazinamide", "Pyrazinamide is an antibiotic that fights bacteria in the body. It is used to treat tuberculosis in combination with other medications.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ethambutol", "Ethambutol is an antibiotic that fights bacteria in the body. It is used to treat tuberculosis in combination with other medications.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Cycloserine", "Cycloserine is an antibiotic that fights bacteria in the body. It is used to treat tuberculosis in combination with other medications.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Amphotericin B", "Amphotericin B is an antifungal medication that fights fungal infections in the body. It is used to treat serious or severe fungal infections, including fungal meningitis, cryptococcal meningitis, histoplasmosis, and candidiasis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Fluconazole", "Fluconazole is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including vaginal yeast infections, oral thrush, esophageal candidiasis, and cryptococcal meningitis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Itraconazole", "Itraconazole is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including fungal nail infections, vaginal yeast infections, oral thrush, and histoplasmosis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ketoconazole", "Ketoconazole is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including fungal skin infections, fungal nail infections, oral thrush, and vaginal yeast infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Terbinafine", "Terbinafine is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including fungal nail infections and ringworm.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Caspofungin", "Caspofungin is an echinocandin antifungal medication that fights fungal infections in the body. It is used to treat serious or severe fungal infections, including candidemia, esophageal candidiasis, and invasive aspergillosis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Micafungin", "Micafungin is an echinocandin antifungal medication that fights fungal infections in the body. It is used to treat serious or severe fungal infections, including candidemia and esophageal candidiasis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Anidulafungin", "Anidulafungin is an echinocandin antifungal medication that fights fungal infections in the body. It is used to treat serious or severe fungal infections, including candidemia and invasive candidiasis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Nystatin", "Nystatin is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including oral thrush, esophageal candidiasis, and diaper rash caused by yeast.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Miconazole", "Miconazole is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including vaginal yeast infections, oral thrush, and ringworm.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clotrimazole", "Clotrimazole is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including vaginal yeast infections, oral thrush, and ringworm.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Econazole", "Econazole is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including vaginal yeast infections, jock itch, and ringworm.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Flucytosine", "Flucytosine is an antifungal medication that fights fungal infections in the body. It is used to treat many different types of fungal infections, including cryptococcal meningitis and candidiasis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Pentamidine", "Pentamidine is an antifungal medication that fights fungal infections in the body. It is used to treat serious or severe fungal infections, including pneumonia caused by Pneumocystis jirovecii.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ivermectin", "Ivermectin is an antiparasitic medication that fights parasites in the body. It is used to treat many different types of parasitic infections, including onchocerciasis, strongyloidiasis, and lymphatic filariasis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Mebendazole", "Mebendazole is an anthelmintic medication that fights parasites in the body. It is used to treat many different types of parasitic infections, including roundworm, hookworm, whipworm, and pinworm.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Praziquantel", "Praziquantel is an anthelmintic medication that fights parasites in the body. It is used to treat many different types of parasitic infections, including schistosomiasis, liver fluke infections, and tapeworm infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Albendazole", "Albendazole is an anthelmintic medication that fights parasites in the body. It is used to treat many different types of parasitic infections, including roundworm, hookworm, whipworm, and tapeworm.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Diethylcarbamazine", "Diethylcarbamazine is an anthelmintic medication that fights parasites in the body. It is used to treat lymphatic filariasis, river blindness, and other parasitic infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Quinine", "Quinine is an antimalarial medication that fights parasites in the body. It is used to treat malaria caused by Plasmodium falciparum and other species of Plasmodium.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Artemether-Lumefantrine", "Artemether-lumefantrine is an antimalarial medication that fights parasites in the body. It is used to treat malaria caused by Plasmodium falciparum.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Atovaquone-Proguanil", "Atovaquone-proguanil is an antimalarial medication that fights parasites in the body. It is used to treat and prevent malaria caused by Plasmodium falciparum and other species of Plasmodium.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Doxycycline", "Doxycycline is an antibiotic that fights bacteria in the body. It is also used as an antimalarial medication to prevent malaria in people traveling to malaria-endemic areas.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Chloroquine", "Chloroquine is an antimalarial medication that fights parasites in the body. It is used to treat and prevent malaria caused by Plasmodium falciparum and other species of Plasmodium.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Mefloquine", "Mefloquine is an antimalarial medication that fights parasites in the body. It is used to treat and prevent malaria caused by Plasmodium falciparum and other species of Plasmodium.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Primaquine", "Primaquine is an antimalarial medication that fights parasites in the body. It is used to treat and prevent malaria caused by Plasmodium vivax and Plasmodium ovale.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Artesunate", "Artesunate is an antimalarial medication that fights parasites in the body. It is used to treat severe malaria caused by Plasmodium falciparum.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dihydroartemisinin-Piperaquine", "Dihydroartemisinin-piperaquine is an antimalarial medication that fights parasites in the body. It is used to treat and prevent malaria caused by Plasmodium falciparum and other species of Plasmodium.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Tafenoquine", "Tafenoquine is an antimalarial medication that fights parasites in the body. It is used to prevent relapse of Plasmodium vivax malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Sulfadoxine-Pyrimethamine", "Sulfadoxine-pyrimethamine is an antimalarial medication that fights parasites in the body. It is used to treat and prevent malaria caused by Plasmodium falciparum.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Chlorproguanil-Dapsone", "Chlorproguanil-dapsone is an antimalarial medication that fights parasites in the body. It is used to treat and prevent malaria caused by Plasmodium falciparum.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Methylene Blue", "Methylene blue is an antimalarial medication that fights parasites in the body. It is used to treat methemoglobinemia caused by certain medications and chemicals.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Pentoxifylline", "Pentoxifylline is a xanthine derivative medication that improves blood flow by decreasing viscosity (thickness) of blood. It is used to treat intermittent claudication (pain in the legs caused by poor blood circulation).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Cilostazol", "Cilostazol is a phosphodiesterase inhibitor medication that improves blood flow by relaxing blood vessels and preventing blood clots. It is used to treat intermittent claudication (pain in the legs caused by poor blood circulation).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Nicorandil", "Nicorandil is a potassium channel activator medication that improves blood flow by relaxing blood vessels and reducing the workload on the heart. It is used to treat angina (chest pain) caused by coronary artery disease.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Isosorbide Dinitrate", "Isosorbide dinitrate is a nitrate medication that improves blood flow by dilating blood vessels. It is used to prevent angina (chest pain) caused by coronary artery disease.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Isosorbide Mononitrate", "Isosorbide mononitrate is a nitrate medication that improves blood flow by dilating blood vessels. It is used to prevent angina (chest pain) caused by coronary artery disease.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Nitroglycerin", "Nitroglycerin is a nitrate medication that improves blood flow by dilating blood vessels. It is used to prevent angina (chest pain) caused by coronary artery disease.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ranolazine", "Ranolazine is an antianginal medication that improves blood flow to the heart by reducing the release of fatty acids. It is used to treat chronic angina (chest pain) caused by coronary artery disease.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Digoxin", "Digoxin is a cardiac glycoside medication that improves heart function by increasing the force of contraction. It is used to treat heart failure and atrial fibrillation (irregular heart rhythm).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dobutamine", "Dobutamine is a sympathomimetic medication that improves heart function by increasing the force of contraction. It is used to treat heart failure and cardiogenic shock (sudden heart failure).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Milrinone", "Milrinone is a phosphodiesterase inhibitor medication that improves heart function by increasing the force of contraction. It is used to treat heart failure and cardiogenic shock (sudden heart failure).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Amiodarone", "Amiodarone is an antiarrhythmic medication that controls irregular heartbeats by stabilizing the heart's electrical activity. It is used to treat ventricular arrhythmias and atrial fibrillation (irregular heart rhythm).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Flecainide", "Flecainide is an antiarrhythmic medication that controls irregular heartbeats by stabilizing the heart's electrical activity. It is used to treat ventricular arrhythmias and atrial fibrillation (irregular heart rhythm).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Propafenone", "Propafenone is an antiarrhythmic medication that controls irregular heartbeats by stabilizing the heart's electrical activity. It is used to treat ventricular arrhythmias and atrial fibrillation (irregular heart rhythm).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Procainamide", "Procainamide is an antiarrhythmic medication that controls irregular heartbeats by stabilizing the heart's electrical activity. It is used to treat ventricular arrhythmias and atrial fibrillation (irregular heart rhythm).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Quinidine", "Quinidine is an antiarrhythmic medication that controls irregular heartbeats by stabilizing the heart's electrical activity. It is used to treat ventricular arrhythmias and atrial fibrillation (irregular heart rhythm).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Verapamil", "Verapamil is a calcium channel blocker medication that improves blood flow to the heart by relaxing blood vessels. It is used to treat high blood pressure, angina (chest pain), and certain heart rhythm disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Diltiazem", "Diltiazem is a calcium channel blocker medication that improves blood flow to the heart by relaxing blood vessels. It is used to treat high blood pressure, angina (chest pain), and certain heart rhythm disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Amlodipine", "Amlodipine is a calcium channel blocker medication that improves blood flow to the heart by relaxing blood vessels. It is used to treat high blood pressure, angina (chest pain), and certain heart rhythm disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Felodipine", "Felodipine is a calcium channel blocker medication that improves blood flow to the heart by relaxing blood vessels. It is used to treat high blood pressure and angina (chest pain).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Nifedipine", "Nifedipine is a calcium channel blocker medication that improves blood flow to the heart by relaxing blood vessels. It is used to treat high blood pressure and angina (chest pain).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Nicardipine", "Nicardipine is a calcium channel blocker medication that improves blood flow to the heart by relaxing blood vessels. It is used to treat high blood pressure and angina (chest pain).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Hydralazine", "Hydralazine is a vasodilator medication that improves blood flow by relaxing blood vessels. It is used to treat high blood pressure and heart failure.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Minoxidil", "Minoxidil is a vasodilator medication that improves blood flow by relaxing blood vessels. It is used to treat high blood pressure and hair loss.", getRandomDiscount(), getRandomRating())));
  newAdapter1 = new MedicineExtraAdapter1(simpleone);
  firsrecyv.setAdapter(newAdapter1);


  secondrecycleview = view.findViewById(R.id.Second_recycleview);
  secondrecycleview.setHasFixedSize(true);
  GridLayoutManager gridLayoutManager = new GridLayoutManager(getContext(), 2, LinearLayoutManager.HORIZONTAL, false);
  secondrecycleview.setLayoutManager(gridLayoutManager);
  simpleone = new ArrayList<>();
  simpleone.add(new ArrayList(Arrays.asList("Pantoprazole", "It is a medicine", "6% Off $34", "3.2")));
  simpleone.add(new ArrayList<>(Arrays.asList("Metoclopramide", "Metoclopramide is a medication used to treat certain conditions of the stomach and intestines. It works by increasing the movements or contractions of the stomach and intestines.", "1% off Rs 350", "4.5")));
  simpleone.add(new ArrayList<>(Arrays.asList("Ondansetron", "Ondansetron is a medication used to prevent nausea and vomiting caused by cancer chemotherapy, radiation therapy, and surgery. It works by blocking the action of serotonin, a natural substance that may cause nausea and vomiting.", "7% off Rs 160", "3.5")));
  simpleone.add(new ArrayList<>(Arrays.asList("Amoxicillin", "Amoxicillin is a penicillin antibiotic that fights bacteria. Amoxicillin is used to treat many different types of infection caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Domperidone", "Domperidone is a medication used to relieve symptoms of nausea and vomiting. It works by blocking the action of a chemical messenger in the brain that may cause nausea and vomiting, and by increasing the movements or contractions of the stomach and intestines.", "8% off Rs 750", "3.9")));
  simpleone.add(new ArrayList<>(Arrays.asList("Simethicone", "Simethicone is an anti-foaming agent that works by breaking up gas bubbles in the stomach and intestines. It is used to relieve symptoms of gas such as belching, bloating, and feelings of pressure/discomfort in the stomach/gut.", "1% off Rs 350", "4.5")));
  simpleone.add(new ArrayList<>(Arrays.asList("Lansoprazole", "Lansoprazole is a proton pump inhibitor (PPI) used to treat certain stomach and esophagus problems (such as acid reflux, ulcers). It works by decreasing the amount of acid your stomach makes.", "8% off Rs 650", "4.5")));
  simpleone.add(new ArrayList<>(Arrays.asList("Docusate", "Docusate is a stool softener used to treat or prevent constipation, and to reduce pain or rectal damage caused by hard stools or by straining during bowel movements.", "50% off Rs 250", "2.8")));
  simpleone.add(new ArrayList<>(Arrays.asList("Bisacodyl", "Bisacodyl is a laxative used to treat constipation. It may also be used to clean out the intestines before a bowel examination/surgery.", "60% off Rs 550", "4.5")));
  simpleone.add(new ArrayList<>(Arrays.asList("Senna", "Senna is a medication used to treat constipation and also to empty the bowels before diagnostic tests such as colonoscopy. It works by increasing the movement of the intestines.", "90% off Rs 1250", "1.5")));
  simpleone.add(new ArrayList<>(Arrays.asList("Lactulose", "Lactulose is a laxative used to treat constipation. It is also used to treat or prevent complications of liver disease (hepatic encephalopathy). It works by drawing water into the colon, which softens the stool and causes it to swell.", "60% off Rs 450", "4.5")));
  simpleone.add(new ArrayList<>(Arrays.asList("Psyllium", "Psyllium is a bulk-forming fiber laxative used to treat constipation. It absorbs liquid in the intestines, swells, and forms a bulky stool, which is easy to pass.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ferrous sulfate", "Ferrous sulfate is an iron supplement used to treat or prevent low blood levels of iron (such as those caused by anemia or during pregnancy). Iron is an important mineral that the body needs to produce red blood cells and keep you in good health.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Folic acid", "Folic acid is a type of B vitamin that is normally found in foods such as dried beans, peas, lentils, oranges, whole-wheat products, liver, asparagus, beets, broccoli, brussels sprouts, and spinach.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Multivitamin", "A multivitamin is a preparation intended to serve as a dietary supplement with vitamins, dietary minerals, and other nutritional elements. Such preparations are available in the form of tablets, capsules, pastilles, powders, liquids, or injectable formulations.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Calcium carbonate", "Calcium carbonate is a dietary supplement used when the amount of calcium taken in the diet is not enough. Calcium is needed by the body for healthy bones, muscles, nervous system, and heart.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Vitamin D", "Vitamin D is a fat-soluble vitamin that helps your body absorb calcium and phosphorus. Having the right amount of vitamin D, calcium, and phosphorus is important for building and keeping strong bones.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Vitamin B12", "Vitamin B12 is a nutrient that helps keep the body's nerve and blood cells healthy and helps make DNA, the genetic material in all cells. Vitamin B12 also helps prevent a type of anemia called megaloblastic anemia that makes people tired and weak.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Vitamin C", "Vitamin C, also known as ascorbic acid, is necessary for the growth, development, and repair of all body tissues. It's involved in many body functions, including the formation of collagen, absorption of iron, the immune system, wound healing, and the maintenance of cartilage, bones, and teeth.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Zinc oxide", "Zinc oxide is a mineral. Zinc is important for growth and for the development and health of body tissues. Zinc oxide used in this medicine is a skin protectant that soothes minor skin irritations.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dextromethorphan", "Dextromethorphan is a cough suppressant used to relieve coughing. It affects the signals in the brain that trigger cough reflex.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Guaifenesin", "Guaifenesin is an expectorant used to help clear mucus or phlegm (pronounced flem) from the chest when you have congestion from the common cold, hay fever, or other respiratory allergies.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Phenylephrine", "Phenylephrine is a decongestant used to relieve nasal discomfort caused by colds, allergies, and hay fever. It works by narrowing the blood vessels in the nasal passages.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Pseudoephedrine", "Pseudoephedrine is a decongestant that shrinks blood vessels in the nasal passages. Dilated blood vessels can cause nasal congestion (stuffy nose). Pseudoephedrine is used to treat nasal and sinus congestion, or congestion of the tubes that drain fluid from your inner ears, called the eustachian (yoo-STAY-shun) tubes.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Acetaminophen", "Acetaminophen is a pain reliever and a fever reducer. It is used to treat many conditions such as headache, muscle aches, arthritis, backache, toothaches, colds, and fevers.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dextrose", "Dextrose is a form of glucose (sugar). Dextrose 5% in water is injected into a vein through an IV to replace lost fluids and provide carbohydrates to the body.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Glucose", "Glucose is a simple sugar that your body gets from food. Your body uses glucose for energy. It is stored in your liver and muscles for when it is needed. When you eat food, your body breaks down the sugars and starches into glucose.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Insulin", "Insulin is a hormone that works by lowering levels of glucose (sugar) in the blood. Insulin glargine is a long-acting insulin that starts to work several hours after injection and keeps working evenly for 24 hours.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Epinephrine", "Epinephrine, also known as adrenaline, is a medication and hormone. As a medication, it is used to treat a number of conditions, including anaphylaxis, cardiac arrest, and superficial bleeding.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Albuterol", "Albuterol is a bronchodilator that relaxes muscles in the airways and increases air flow to the lungs. Albuterol inhalation is used to treat or prevent bronchospasm, or narrowing of the airways in the lungs, in people with asthma or certain types of chronic obstructive pulmonary disease (COPD).", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Beclometasone", "Beclometasone is a corticosteroid. It is used to prevent asthma attacks. It works by decreasing irritation and swelling in the airways, which helps to control or prevent asthma symptoms.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Budesonide", "Budesonide is a corticosteroid that prevents the release of substances in the body that cause inflammation. Budesonide inhalation is used to prevent asthma attacks in adults and children who are at least 6 years old.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Fluticasone", "Fluticasone is a steroid. It prevents the release of substances in the body that cause inflammation. Fluticasone inhalation is used to prevent asthma attacks. It will not treat an asthma attack that has already begun.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Montelukast", "Montelukast is a leukotriene receptor antagonist. It works by blocking the action of certain natural substances that cause swelling, tightening of the airways, and other symptoms of asthma and allergies.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Salbutamol", "Salbutamol is a bronchodilator. It works by relaxing the muscles in the airways and making breathing easier. Salbutamol inhalation is used to treat or prevent bronchospasm in people with reversible obstructive airway disease.", getRandomDiscount(), getRandomRating())));

  bestSellerAdapter = new MedicineExtraAdapter2(simpleone);
  secondrecycleview.setAdapter(bestSellerAdapter);

  thirdrecycleview = view.findViewById(R.id.third_recycleview);
  thirdrecycleview.setHasFixedSize(true);
  thirdrecycleview.setLayoutManager(new GridLayoutManager(getContext(), 2, LinearLayoutManager.HORIZONTAL, false));


  simpleone = new ArrayList<>();

  simpleone.add(new ArrayList<>(Arrays.asList("Chlorthalidone", "Chlorthalidone is a thiazide diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Indapamide", "Indapamide is a thiazide diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Bendroflumethiazide", "Bendroflumethiazide is a thiazide diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Amiloride", "Amiloride is a potassium-sparing diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Triamterene", "Triamterene is a potassium-sparing diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Spironolactone", "Spironolactone is a potassium-sparing diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure, heart failure, and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Eplerenone", "Eplerenone is a potassium-sparing diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure and heart failure.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Furosemide", "Furosemide is a loop diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure, heart failure, and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Torsemide", "Torsemide is a loop diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure, heart failure, and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Bumetanide", "Bumetanide is a loop diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure, heart failure, and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ethacrynic Acid", "Ethacrynic acid is a loop diuretic medication that increases urine production and reduces fluid retention. It is used to treat high blood pressure, heart failure, and edema (fluid retention) caused by certain medical conditions.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Digoxin Immune Fab", "Digoxin immune fab is an antidote medication used to treat digoxin toxicity (overdose). It works by binding to digoxin and preventing it from exerting harmful effects on the body.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Atropine", "Atropine is an antidote medication used to treat poisoning by organophosphate pesticides and nerve agents. It works by blocking the action of acetylcholine in the body.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Prussian Blue", "Prussian blue is an antidote medication used to treat thallium and radioactive cesium poisoning. It works by binding to thallium and radioactive cesium in the body, allowing them to be excreted in the urine.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dimercaprol", "Dimercaprol is an antidote medication used to treat poisoning by arsenic, mercury, gold, and other heavy metals. It works by binding to heavy metals in the body and forming compounds that can be excreted in the urine.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Deferoxamine", "Deferoxamine is an antidote medication used to treat iron poisoning. It works by binding to iron in the body and forming a compound that can be excreted in the urine.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Naloxone", "Naloxone is an antidote medication used to reverse the effects of opioid overdose, including respiratory depression, sedation, and hypotension. It works by blocking the action of opioids in the body.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Flumazenil", "Flumazenil is an antidote medication used to reverse the effects of benzodiazepine overdose, including sedation and respiratory depression. It works by blocking the action of benzodiazepines in the body.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Physostigmine", "Physostigmine is an antidote medication used to reverse the effects of anticholinergic poisoning, including delirium, hallucinations, and agitation. It works by increasing the levels of acetylcholine in the brain.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Glucagon", "Glucagon is an antidote medication used to treat severe hypoglycemia (low blood sugar) in people with diabetes who are unconscious or unable to eat. It works by increasing blood sugar levels.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Activated Charcoal", "Activated charcoal is an antidote medication used to treat poisoning by adsorbing toxins in the gastrointestinal tract. It works by binding to toxins and preventing them from being absorbed into the bloodstream.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Sodium Bicarbonate", "Sodium bicarbonate is an antidote medication used to treat poisoning by acidic substances, such as aspirin and methanol. It works by neutralizing acids and increasing the pH of the blood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Calcium Gluconate", "Calcium gluconate is an antidote medication used to treat poisoning by calcium channel blockers and fluoride. It works by increasing calcium levels in the blood and counteracting the effects of calcium channel blockers and fluoride.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Sodium Thiosulfate", "Sodium thiosulfate is an antidote medication used to treat poisoning by cyanide. It works by reacting with cyanide to form thiocyanate, which is less toxic and can be excreted in the urine.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Hydroxocobalamin", "Hydroxocobalamin is an antidote medication used to treat poisoning by cyanide. It works by binding to cyanide to form cyanocobalamin (vitamin B12), which is less toxic and can be excreted in the urine.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Diazepam", "Diazepam is a benzodiazepine medication that works in the brain to treat anxiety, muscle spasms, and seizures. It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Alprazolam", "Alprazolam is a benzodiazepine medication that works in the brain to treat anxiety and panic disorders. It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Lorazepam", "Lorazepam is a benzodiazepine medication that works in the brain to treat anxiety, insomnia, and seizures. It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clonazepam", "Clonazepam is a benzodiazepine medication that works in the brain to treat seizures, panic disorders, and certain movement disorders. It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Temazepam", "Temazepam is a benzodiazepine medication that works in the brain to treat insomnia (trouble sleeping). It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Oxazepam", "Oxazepam is a benzodiazepine medication that works in the brain to treat anxiety and alcohol withdrawal symptoms. It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Midazolam", "Midazolam is a benzodiazepine medication that works in the brain to produce sedation and reduce anxiety. It is used for anesthesia, procedural sedation, and treatment of seizures. It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Flurazepam", "Flurazepam is a benzodiazepine medication that works in the brain to treat insomnia (trouble sleeping). It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Quazepam", "Quazepam is a benzodiazepine medication that works in the brain to treat insomnia (trouble sleeping). It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Triazolam", "Triazolam is a benzodiazepine medication that works in the brain to produce sedation and reduce anxiety. It is used for short-term treatment of insomnia (trouble sleeping). It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Zolpidem", "Zolpidem is a non-benzodiazepine medication that works in the brain to treat insomnia (trouble sleeping). It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Eszopiclone", "Eszopiclone is a non-benzodiazepine medication that works in the brain to treat insomnia (trouble sleeping). It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Zaleplon", "Zaleplon is a non-benzodiazepine medication that works in the brain to treat insomnia (trouble sleeping). It works by enhancing the effects of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ramelteon", "Ramelteon is a melatonin receptor agonist medication that works in the brain to treat insomnia (trouble sleeping). It works by mimicking the action of melatonin, a hormone that regulates sleep-wake cycles.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Buspirone", "Buspirone is an anxiolytic medication that works in the brain to treat anxiety disorders. It works by binding to serotonin and dopamine receptors and modulating their activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Hydroxyzine", "Hydroxyzine is an antihistamine medication that works in the brain to treat anxiety and tension. It works by blocking the action of histamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Diphenhydramine", "Diphenhydramine is an antihistamine medication that works in the brain to treat anxiety, insomnia, and allergic reactions. It works by blocking the action of histamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Doxylamine", "Doxylamine is an antihistamine medication that works in the brain to treat insomnia (trouble sleeping) and allergic reactions. It works by blocking the action of histamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Promethazine", "Promethazine is an antihistamine medication that works in the brain to treat nausea, vomiting, and allergic reactions. It works by blocking the action of histamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Meclizine", "Meclizine is an antihistamine medication that works in the brain to treat motion sickness and vertigo (dizziness). It works by blocking the action of histamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Cyclizine", "Cyclizine is an antihistamine medication that works in the brain to treat motion sickness and vertigo (dizziness). It works by blocking the action of histamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dimenhydrinate", "Dimenhydrinate is an antihistamine medication that works in the brain to treat motion sickness and vertigo (dizziness). It works by blocking the action of histamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Scopolamine", "Scopolamine is an anticholinergic medication that works in the brain to treat motion sickness and nausea. It works by blocking the action of acetylcholine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ondansetron", "Ondansetron is a serotonin receptor antagonist medication that works in the brain to treat nausea and vomiting. It works by blocking the action of serotonin, a neurotransmitter involved in nausea and vomiting.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Metoclopramide", "Metoclopramide is a dopamine receptor antagonist medication that works in the brain to treat nausea, vomiting, and gastroparesis (delayed stomach emptying). It works by increasing the movement of food through the stomach and intestines.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Domperidone", "Domperidone is a dopamine receptor antagonist medication that works in the brain to treat nausea, vomiting, and gastroparesis (delayed stomach emptying). It works by increasing the movement of food through the stomach and intestines.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Prochlorperazine", "Prochlorperazine is a dopamine receptor antagonist medication that works in the brain to treat nausea, vomiting, and vertigo (dizziness). It works by blocking the action of dopamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Promethazine", "Promethazine is a dopamine receptor antagonist medication that works in the brain to treat nausea, vomiting, and allergic reactions. It works by blocking the action of dopamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Droperidol", "Droperidol is a dopamine receptor antagonist medication that works in the brain to treat nausea, vomiting, and agitation. It works by blocking the action of dopamine and decreasing activity in the central nervous system.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dexamethasone", "Dexamethasone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and certain types of cancer.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Prednisone", "Prednisone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Methylprednisolone", "Methylprednisolone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Hydrocortisone", "Hydrocortisone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Betamethasone", "Betamethasone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Triamcinolone", "Triamcinolone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Fluticasone", "Fluticasone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and asthma.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Budesonide", "Budesonide is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and asthma.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Beclomethasone", "Beclomethasone is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and asthma.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clobetasol", "Clobetasol is a corticosteroid medication that works in the body to reduce inflammation and suppress the immune system. It is used to treat a variety of conditions, including allergic reactions, inflammation, and certain skin disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Tacrolimus", "Tacrolimus is an immunosuppressant medication that works in the body to suppress the immune system. It is used to prevent organ rejection after transplantation and to treat certain autoimmune disorders, such as eczema and psoriasis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Cyclosporine", "Cyclosporine is an immunosuppressant medication that works in the body to suppress the immune system. It is used to prevent organ rejection after transplantation and to treat certain autoimmune disorders, such as psoriasis and rheumatoid arthritis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Sirolimus", "Sirolimus is an immunosuppressant medication that works in the body to suppress the immune system. It is used to prevent organ rejection after transplantation and to treat certain autoimmune disorders, such as rheumatoid arthritis and lupus.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Mycophenolate", "Mycophenolate is an immunosuppressant medication that works in the body to suppress the immune system. It is used to prevent organ rejection after transplantation and to treat certain autoimmune disorders, such as lupus and rheumatoid arthritis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Azathioprine", "Azathioprine is an immunosuppressant medication that works in the body to suppress the immune system. It is used to prevent organ rejection after transplantation and to treat certain autoimmune disorders, such as lupus and rheumatoid arthritis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Methotrexate", "Methotrexate is an immunosuppressant medication that works in the body to suppress the immune system. It is used to treat certain types of cancer, autoimmune disorders, and severe psoriasis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Leflunomide", "Leflunomide is an immunosuppressant medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis and certain autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Etanercept", "Etanercept is a tumor necrosis factor (TNF) inhibitor medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis, psoriasis, and certain autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Adalimumab", "Adalimumab is a tumor necrosis factor (TNF) inhibitor medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis, psoriasis, and certain autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Infliximab", "Infliximab is a tumor necrosis factor (TNF) inhibitor medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis, psoriasis, and certain autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Certolizumab", "Certolizumab is a tumor necrosis factor (TNF) inhibitor medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis, psoriasis, and certain autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Golimumab", "Golimumab is a tumor necrosis factor (TNF) inhibitor medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis, psoriasis, and certain autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Rituximab", "Rituximab is a monoclonal antibody medication that works in the body to suppress the immune system. It is used to treat certain types of cancer, rheumatoid arthritis, and certain autoimmune disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Abatacept", "Abatacept is a selective costimulation modulator medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis, psoriatic arthritis, and juvenile idiopathic arthritis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Tocilizumab", "Tocilizumab is an interleukin-6 (IL-6) receptor antagonist medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis, juvenile idiopathic arthritis, and cytokine release syndrome.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Anakinra", "Anakinra is an interleukin-1 (IL-1) receptor antagonist medication that works in the body to suppress the immune system. It is used to treat rheumatoid arthritis and certain autoinflammatory disorders.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Colchicine", "Colchicine is an anti-inflammatory medication that works in the body to reduce inflammation and pain. It is used to treat gout, familial Mediterranean fever, and pericarditis.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Allopurinol", "Allopurinol is a xanthine oxidase inhibitor medication that works in the body to reduce the production of uric acid. It is used to prevent gout attacks and to treat certain types of kidney stones.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Febuxostat", "Febuxostat is a xanthine oxidase inhibitor medication that works in the body to reduce the production of uric acid. It is used to prevent gout attacks and to treat certain types of kidney stones.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Pegloticase", "Pegloticase is an enzyme medication that works in the body to break down uric acid. It is used to treat gout in people who do not respond to other medications.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Hydroxychloroquine", "Hydroxychloroquine is an antimalarial medication that also has anti-inflammatory properties. It is used to treat malaria, rheumatoid arthritis, and lupus erythematosus.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Chloroquine", "Chloroquine is an antimalarial medication that also has anti-inflammatory properties. It is used to prevent and treat malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Mefloquine", "Mefloquine is an antimalarial medication that works by killing the malaria parasites living inside red blood cells. It is used to prevent and treat malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Artemether", "Artemether is an antimalarial medication that works by killing the malaria parasites living inside red blood cells. It is used to treat severe malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Lumefantrine", "Lumefantrine is an antimalarial medication that works by killing the malaria parasites living inside red blood cells. It is used in combination with other antimalarial medications to treat malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Atovaquone", "Atovaquone is an antimalarial medication that works by killing the malaria parasites living inside red blood cells. It is used in combination with other antimalarial medications to prevent and treat malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Proguanil", "Proguanil is an antimalarial medication that works by killing the malaria parasites living inside red blood cells. It is used in combination with other antimalarial medications to prevent and treat malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Doxycycline", "Doxycycline is an antibiotic medication that works by stopping the growth of bacteria. It is used to treat bacterial infections, acne, and certain types of malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Tetracycline", "Tetracycline is an antibiotic medication that works by stopping the growth of bacteria. It is used to treat bacterial infections, acne, and certain types of malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clindamycin", "Clindamycin is an antibiotic medication that works by stopping the growth of bacteria. It is used to treat bacterial infections, acne, and certain types of malaria.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Metronidazole", "Metronidazole is an antibiotic medication that works by stopping the growth of bacteria and parasites. It is used to treat bacterial infections, parasitic infections, and certain types of diarrhea.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Azithromycin", "Azithromycin is an antibiotic medication that works by stopping the growth of bacteria. It is used to treat bacterial infections, including respiratory infections, skin infections, and sexually transmitted infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Amoxicillin", "Amoxicillin is a penicillin antibiotic that fights bacteria. Amoxicillin is used to treat many different types of infection caused by bacteria, such as tonsillitis, bronchitis, pneumonia, and infections of the ear, nose, throat, skin, or urinary tract.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Cephalexin", "Cephalexin is a cephalosporin antibiotic that fights bacteria. It is used to treat bacterial infections, including respiratory infections, skin infections, ear infections, and urinary tract infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ciprofloxacin", "Ciprofloxacin is a fluoroquinolone antibiotic that fights bacteria. It is used to treat bacterial infections, including urinary tract infections, respiratory infections, skin infections, and gastrointestinal infections.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Levofloxacin", "Levofloxacin is a fluoroquinolone antibiotic that fights bacteria. It is used to treat bacterial infections, including respiratory infections, skin infections, urinary tract", getRandomDiscount(), getRandomRating())));
  newAdapter2 = new MedicineExtraAdapter1(simpleone);
  thirdrecycleview.setAdapter(newAdapter2);

  simpleone = new ArrayList<>();
  simpleone.add(new ArrayList<>(Arrays.asList("Warfarin", "Warfarin is an anticoagulant medication that works by inhibiting the synthesis of vitamin K-dependent clotting factors in the liver. It is used to prevent blood clots, stroke, and heart attacks.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clopidogrel", "Clopidogrel is an antiplatelet medication that works by inhibiting the binding of adenosine diphosphate (ADP) to platelet receptors. It is used to prevent blood clots, stroke, and heart attacks.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Heparin", "Heparin is an anticoagulant medication that works by enhancing the activity of antithrombin III, an enzyme that inhibits the formation of blood clots. It is used to prevent and treat blood clots.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Enoxaparin", "Enoxaparin is an anticoagulant medication that works by enhancing the activity of antithrombin III, an enzyme that inhibits the formation of blood clots. It is used to prevent and treat blood clots.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Rivaroxaban", "Rivaroxaban is an anticoagulant medication that works by inhibiting factor Xa, a key component of the blood clotting process. It is used to prevent and treat blood clots, stroke, and pulmonary embolism.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Apixaban", "Apixaban is an anticoagulant medication that works by inhibiting factor Xa, a key component of the blood clotting process. It is used to prevent and treat blood clots, stroke, and pulmonary embolism.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dabigatran", "Dabigatran is an anticoagulant medication that works by inhibiting thrombin, a key enzyme in the blood clotting process. It is used to prevent and treat blood clots, stroke, and pulmonary embolism.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Epoetin alfa", "Epoetin alfa is a synthetic form of erythropoietin, a hormone that stimulates the production of red blood cells in the bone marrow. It is used to treat anemia associated with chronic kidney disease and cancer chemotherapy.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Darbepoetin alfa", "Darbepoetin alfa is a synthetic form of erythropoietin, a hormone that stimulates the production of red blood cells in the bone marrow. It is used to treat anemia associated with chronic kidney disease and cancer chemotherapy.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ferrous sulfate", "Ferrous sulfate is an iron supplement that is used to prevent and treat iron deficiency anemia. It works by increasing the production of red blood cells in the bone marrow.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Folic acid", "Folic acid is a vitamin supplement that is used to prevent and treat folate deficiency anemia. It works by helping the body produce and maintain new cells, including red blood cells.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Vitamin B12", "Vitamin B12 is a vitamin supplement that is used to prevent and treat vitamin B12 deficiency anemia. It works by helping the body produce red blood cells and maintain proper neurological function.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ibuprofen", "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) that works by inhibiting the production of prostaglandins, chemicals that cause inflammation and pain in the body. It is used to treat pain, inflammation, and fever.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Naproxen", "Naproxen is a nonsteroidal anti-inflammatory drug (NSAID) that works by inhibiting the production of prostaglandins, chemicals that cause inflammation and pain in the body. It is used to treat pain, inflammation, and fever.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Acetaminophen", "Acetaminophen is a pain reliever and fever reducer that works by inhibiting the production of prostaglandins in the brain. It is used to treat pain and fever, but it does not reduce inflammation like NSAIDs do.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Aspirin", "Aspirin is a nonsteroidal anti-inflammatory drug (NSAID) that works by inhibiting the production of prostaglandins, chemicals that cause inflammation and pain in the body. It is used to treat pain, inflammation, and fever, and to prevent blood clots.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Alendronate", "Alendronate is a bisphosphonate medication that works by slowing down the breakdown of bone and increasing bone density. It is used to prevent and treat osteoporosis, a condition characterized by weak and brittle bones.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Risedronate", "Risedronate is a bisphosphonate medication that works by slowing down the breakdown of bone and increasing bone density. It is used to prevent and treat osteoporosis, a condition characterized by weak and brittle bones.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Ibandronate", "Ibandronate is a bisphosphonate medication that works by slowing down the breakdown of bone and increasing bone density. It is used to prevent and treat osteoporosis, a condition characterized by weak and brittle bones.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Zoledronic acid", "Zoledronic acid is a bisphosphonate medication that works by slowing down the breakdown of bone and increasing bone density. It is used to prevent and treat osteoporosis, a condition characterized by weak and brittle bones.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Calcitonin", "Calcitonin is a hormone medication that works by inhibiting the activity of osteoclasts, cells that break down bone tissue. It is used to treat osteoporosis and Paget's disease of bone.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Teriparatide", "Teriparatide is a parathyroid hormone medication that works by stimulating bone formation and increasing bone density. It is used to treat osteoporosis in postmenopausal women and men at high risk of fracture.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Denosumab", "Denosumab is a monoclonal antibody medication that works by inhibiting the activity of osteoclasts, cells that break down bone tissue. It is used to treat osteoporosis and bone metastases in cancer patients.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Calcium carbonate", "Calcium carbonate is a calcium supplement that is used to prevent and treat calcium deficiency. It is important for maintaining strong bones and teeth, and for proper muscle and nerve function.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Vitamin D", "Vitamin D is a vitamin supplement that is important for maintaining strong bones and teeth, and for proper calcium absorption in the body. It is used to prevent and treat vitamin D deficiency.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Fluoxetine", "Fluoxetine is a selective serotonin reuptake inhibitor (SSRI) medication that works in the brain to treat depression, obsessive-compulsive disorder (OCD), and bulimia nervosa. It works by increasing the levels of serotonin, a neurotransmitter that regulates mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Sertraline", "Sertraline is a selective serotonin reuptake inhibitor (SSRI) medication that works in the brain to treat depression, obsessive-compulsive disorder (OCD), panic disorder, and social anxiety disorder. It works by increasing the levels of serotonin, a neurotransmitter that regulates mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Escitalopram", "Escitalopram is a selective serotonin reuptake inhibitor (SSRI) medication that works in the brain to treat depression and generalized anxiety disorder. It works by increasing the levels of serotonin, a neurotransmitter that regulates mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Paroxetine", "Paroxetine is a selective serotonin reuptake inhibitor (SSRI) medication that works in the brain to treat depression, panic disorder, social anxiety disorder, and obsessive-compulsive disorder (OCD). It works by increasing the levels of serotonin, a neurotransmitter that regulates mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Citalopram", "Citalopram is a selective serotonin reuptake inhibitor (SSRI) medication that works in the brain to treat depression and panic disorder. It works by increasing the levels of serotonin, a neurotransmitter that regulates mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Venlafaxine", "Venlafaxine is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that works in the brain to treat depression, generalized anxiety disorder (GAD), and social anxiety disorder. It works by increasing the levels of serotonin and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Duloxetine", "Duloxetine is a serotonin-norepinephrine reuptake inhibitor (SNRI) medication that works in the brain to treat depression, generalized anxiety disorder (GAD), and fibromyalgia. It works by increasing the levels of serotonin and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Bupropion", "Bupropion is an atypical antidepressant medication that works in the brain to treat depression and seasonal affective disorder (SAD). It works by increasing the levels of dopamine and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Mirtazapine", "Mirtazapine is an atypical antidepressant medication that works in the brain to treat depression and anxiety. It works by increasing the levels of serotonin and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Amitriptyline", "Amitriptyline is a tricyclic antidepressant medication that works in the brain to treat depression, anxiety, and certain types of pain. It works by increasing the levels of serotonin and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Imipramine", "Imipramine is a tricyclic antidepressant medication that works in the brain to treat depression and anxiety. It works by increasing the levels of serotonin and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Nortriptyline", "Nortriptyline is a tricyclic antidepressant medication that works in the brain to treat depression and certain types of pain. It works by increasing the levels of serotonin and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clomipramine", "Clomipramine is a tricyclic antidepressant medication that works in the brain to treat obsessive-compulsive disorder (OCD). It works by increasing the levels of serotonin and norepinephrine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Phenelzine", "Phenelzine is a monoamine oxidase inhibitor (MAOI) medication that works in the brain to treat depression. It works by increasing the levels of serotonin, norepinephrine, and dopamine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Tranylcypromine", "Tranylcypromine is a monoamine oxidase inhibitor (MAOI) medication that works in the brain to treat depression. It works by increasing the levels of serotonin, norepinephrine, and dopamine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Selegiline", "Selegiline is a monoamine oxidase inhibitor (MAOI) medication that works in the brain to treat depression and Parkinson's disease. It works by increasing the levels of serotonin, norepinephrine, and dopamine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Isocarboxazid", "Isocarboxazid is a monoamine oxidase inhibitor (MAOI) medication that works in the brain to treat depression. It works by increasing the levels of serotonin, norepinephrine, and dopamine, neurotransmitters that regulate mood.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Dextroamphetamine", "Dextroamphetamine is a central nervous system (CNS) stimulant medication that works in the brain to treat attention deficit hyperactivity disorder (ADHD) and narcolepsy. It works by increasing the levels of dopamine and norepinephrine, neurotransmitters that regulate attention and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Methylphenidate", "Methylphenidate is a central nervous system (CNS) stimulant medication that works in the brain to treat attention deficit hyperactivity disorder (ADHD) and narcolepsy. It works by increasing the levels of dopamine and norepinephrine, neurotransmitters that regulate attention and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Atomoxetine", "Atomoxetine is a selective norepinephrine reuptake inhibitor (SNRI) medication that works in the brain to treat attention deficit hyperactivity disorder (ADHD). It works by increasing the levels of norepinephrine, a neurotransmitter that regulates attention and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Guanfacine", "Guanfacine is an alpha-2 adrenergic agonist medication that works in the brain to treat attention deficit hyperactivity disorder (ADHD) and high blood pressure. It works by stimulating alpha-2 adrenergic receptors, which regulate attention and blood pressure.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Clonidine", "Clonidine is an alpha-2 adrenergic agonist medication that works in the brain to treat attention deficit hyperactivity disorder (ADHD), high blood pressure, and certain withdrawal symptoms. It works by stimulating alpha-2 adrenergic receptors, which regulate attention, blood pressure, and heart rate.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Lisdexamfetamine", "Lisdexamfetamine is a central nervous system (CNS) stimulant medication that works in the brain to treat attention deficit hyperactivity disorder (ADHD) and binge eating disorder. It works by increasing the levels of dopamine and norepinephrine, neurotransmitters that regulate attention and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Modafinil", "Modafinil is a wakefulness-promoting medication that works in the brain to treat narcolepsy, sleep apnea, and shift work sleep disorder. It works by increasing the levels of dopamine and norepinephrine, neurotransmitters that regulate wakefulness and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Armodafinil", "Armodafinil is a wakefulness-promoting medication that works in the brain to treat narcolepsy, sleep apnea, and shift work sleep disorder. It works by increasing the levels of dopamine and norepinephrine, neurotransmitters that regulate wakefulness and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Zolpidem", "Zolpidem is a sedative-hypnotic medication that works in the brain to treat insomnia. It works by enhancing the activity of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity and promotes sleep.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Eszopiclone", "Eszopiclone is a sedative-hypnotic medication that works in the brain to treat insomnia. It works by enhancing the activity of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity and promotes sleep.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Zaleplon", "Zaleplon is a sedative-hypnotic medication that works in the brain to treat insomnia. It works by enhancing the activity of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity and promotes sleep.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Diphenhydramine", "Diphenhydramine is a first-generation antihistamine medication that works in the brain to treat allergies, hay fever, and insomnia. It works by blocking the effects of histamine, a neurotransmitter that promotes wakefulness and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Doxylamine", "Doxylamine is a first-generation antihistamine medication that works in the brain to treat allergies, hay fever, and insomnia. It works by blocking the effects of histamine, a neurotransmitter that promotes wakefulness and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Promethazine", "Promethazine is a first-generation antihistamine medication that works in the brain to treat allergies, hay fever, and insomnia. It works by blocking the effects of histamine, a neurotransmitter that promotes wakefulness and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Hydroxyzine", "Hydroxyzine is a first-generation antihistamine medication that works in the brain to treat allergies, hay fever, and insomnia. It works by blocking the effects of histamine, a neurotransmitter that promotes wakefulness and alertness.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Melatonin", "Melatonin is a hormone supplement that is used to regulate sleep-wake cycles and treat insomnia. It works by signaling the brain to prepare for sleep and promoting relaxation.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Buspirone", "Buspirone is an anxiolytic medication that works in the brain to treat anxiety disorders and symptoms of anxiety. It works by binding to serotonin and dopamine receptors, neurotransmitters that regulate mood and anxiety.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Pregabalin", "Pregabalin is an anticonvulsant and anxiolytic medication that works in the brain to treat epilepsy, neuropathic pain, and generalized anxiety disorder (GAD). It works by binding to calcium channels in the brain, which reduces the release of neurotransmitters involved in pain and anxiety.", getRandomDiscount(), getRandomRating())));

  simpleone.add(new ArrayList<>(Arrays.asList("Gabapentin", "Gabapentin is an anticonvulsant and analgesic medication that works in the brain to treat epilepsy, neuropathic pain, and restless legs syndrome (RLS). It works by binding to calcium channels in the brain, which reduces the release of neurotransmitters involved in pain and seizure activity.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Diazepam", "Diazepam is a benzodiazepine medication that works in the brain to treat anxiety disorders, alcohol withdrawal symptoms, muscle spasms, and seizures. It works by enhancing the activity of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity and promotes relaxation.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Alprazolam", "Alprazolam is a benzodiazepine medication that works in the brain to treat anxiety disorders and panic disorder. It works by enhancing the activity of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity and promotes relaxation.", getRandomDiscount(), getRandomRating())));
  simpleone.add(new ArrayList<>(Arrays.asList("Lorazepam", "Lorazepam is a benzodiazepine medication that works in the brain to treat anxiety disorders, alcohol withdrawal symptoms, and seizures. It works by enhancing the activity of gamma-aminobutyric acid (GABA), a neurotransmitter that inhibits brain activity and promotes relaxation.", getRandomDiscount(), getRandomRating())));
  fourrecycleview = view.findViewById(R.id.four_recycleview);
  fourrecycleview.setHasFixedSize(true);
  fourrecycleview.setLayoutManager(new LinearLayoutManager(getContext(), LinearLayoutManager.VERTICAL, false));
  bestSeller = new MedicineExtraAdapter2(simpleone);
  fourrecycleview.setAdapter(bestSeller);
  setupSearch();

  return view;
 }

 private void setupSearch() {
  searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
   @Override
   public boolean onQueryTextSubmit(String query) {
    // Handle search query submission (if needed)
    return true;
   }

   @Override
   public boolean onQueryTextChange(String newText) {
    filterData(newText);

    return true;
   }
  });
 }
 private void filterData(String query) {
  String lowercaseQuery = query.toLowerCase();
  if (newAdapter1 != null) {
   newAdapter1.getFilter().filter(lowercaseQuery);
  }
  if (newAdapter2 != null) {
   newAdapter2.getFilter().filter(lowercaseQuery);
  }
  if (bestSeller != null) {
   bestSeller.getFilter().filter(lowercaseQuery);
  }
  if (bestSellerAdapter != null) {
   bestSellerAdapter.getFilter().filter(lowercaseQuery);
  }
  if (lowercaseQuery.isEmpty()) {
   if (newAdapter1 != null) {
    newAdapter1.resetData();
   }
   if (newAdapter2 != null) {
    newAdapter2.resetData();
   }
   if (bestSeller != null) {
    bestSeller.resetData();
   }
   if (bestSellerAdapter != null) {
    bestSellerAdapter.resetData();
   }
  }
 }


 private static String getRandomDiscount() {
        Random random = new Random();
        int r= random.nextInt(99) + 1;
        int price=  random.nextInt(1901) + 100;
        return r+"% off Rs "+price;
    }

    private static String getRandomRating() {
        Random random=new Random();
        float f= random.nextFloat() * 5;
        return String.valueOf(f);
    }
}